ENGINE_PREFIX: str = "v2/engine"
HUB_PREFIX: str = "v2/hub"
DESCRIPTION_MAX_LENGTH = 500

DL_BUFFER_SIZE = 500
DL_BUFFER_TIMEOUT = 60  # seconds

DEFAULT_COLLECTION = "default"
DEFAULT_SORT_FIELD = "timestamp"
