image: python:3.8

pipelines:
  branches:
    jfrogintegration: &shared
      - step:
          name: upload library to jfrog
          script:
            - bash -e deployconfig.bash
            - python setup.py bdist_wheel upload -r splightlib
            - rm ~/.pypirc;
    main: *shared
