apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: {{ namespace }}
    name: "{{id}}"
    labels:
        id: "{{id}}"
        external_id: "{{external_id}}"
        type: {{type}}
        version: "{{version}}"
spec:
    replicas: 1
    selector:
        matchLabels:
            id: "{{id}}"
            external_id: "{{external_id}}"
            type: {{type}}
            version: "{{version}}"
    template:
        metadata:
            labels:
                id: "{{id}}"
                external_id: "{{external_id}}"
                type: {{type}}
                version: "{{version}}"
        spec:
            imagePullSecrets:
                - name: awsecr-cred
            serviceAccountName: {{serviceaccount}}
            serviceAccount: {{serviceaccount}}
            containers:
                - name: "{{id}}"
                  image: {{dockerimg}}
                  command: ["python", "runner.py"]
                  args: ["-r", '{{run_spec}}']
                  imagePullPolicy: "Always"
                  tty: true
                  securityContext:
                    privileged: true
                  livenessProbe:
                    exec:
                        command:
                          - sh
                          - -c
                          - ls /tmp/ | grep -q healthy_
                    initialDelaySeconds: 300
                    periodSeconds: 5
                  envFrom:
                    - configMapRef:
                        name: {{configmap}}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ namespace }}
  name: {{service}}
  labels:
    id: "{{id}}"
    external_id: "{{external_id}}"
    type: {{type}}
    version: "{{version}}"
spec:
  selector:
      id: "{{id}}"
      external_id: "{{external_id}}"
      type: {{type}}
      version: "{{version}}"
  ports:
    - name: proxy
      protocol: TCP
      port: 1080
      targetPort: 1080
