from splight_lib.constants import ENGINE_PREFIX, HUB_PREFIX

MODEL_NAME_MAP = {
    "advancedfilter": f"{ENGINE_PREFIX}/alert/advancedfilters/",
    "action": f"{ENGINE_PREFIX}/asset/actions/",
    "alert": f"{ENGINE_PREFIX}/alert/alerts/",
    "asset": f"{ENGINE_PREFIX}/asset/assets/",
    "assetrelationship": f"{ENGINE_PREFIX}/asset/relations/",
    "tag": f"{ENGINE_PREFIX}/tags/",
    "assetkind": f"{ENGINE_PREFIX}/asset/kinds/",
    "attribute": f"{ENGINE_PREFIX}/asset/attributes/",
    "battery": f"{ENGINE_PREFIX}/asset/batteries/",
    "bus": f"{ENGINE_PREFIX}/asset/buses/",
    "metadata": f"{ENGINE_PREFIX}/metadata/",
    "chart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardactionlistchart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardalerteventschart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardalertlistchart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardassetlistchart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardbarchart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardbargaugechart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardcommandlistchart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardgaugechart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardhistogramchart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardimagechart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardstatchart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardtablechart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardtextchart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "dashboardtimeserieschart": f"{ENGINE_PREFIX}/dashboard/charts/",
    "chartitem": f"{ENGINE_PREFIX}/dashboard/items/",
    "component": f"{ENGINE_PREFIX}/component/components/",
    "componentobject": f"{ENGINE_PREFIX}/component/objects/",
    "dashboard": f"{ENGINE_PREFIX}/dashboard/dashboards/",
    "externalgrid": f"{ENGINE_PREFIX}/asset/external-grids/",
    "file": f"{ENGINE_PREFIX}/files/",
    "filter": f"{ENGINE_PREFIX}/dashboard/filters/",
    "function": f"{ENGINE_PREFIX}/function/functions/",
    "generator": f"{ENGINE_PREFIX}/asset/generators/",
    "grid": f"{ENGINE_PREFIX}/asset/grids/",
    "inverter": f"{ENGINE_PREFIX}/asset/inverters/",
    "line": f"{ENGINE_PREFIX}/asset/lines/",
    "load": f"{ENGINE_PREFIX}/asset/loads/",
    "query": f"{ENGINE_PREFIX}/queries/",
    "routineobject": f"{ENGINE_PREFIX}/component/routines/",
    "secret": f"{ENGINE_PREFIX}/secrets/",
    "segment": f"{ENGINE_PREFIX}/asset/segments/",
    "setpoint": f"{ENGINE_PREFIX}/setpoints/",
    "server": f"{ENGINE_PREFIX}/server/servers/",
    "slackgenerator": f"{ENGINE_PREFIX}/asset/slack-generators/",
    "slackline": f"{ENGINE_PREFIX}/asset/slack-lines/",
    "tab": f"{ENGINE_PREFIX}/dashboard/tabs/",
    "threewindingtransformer": f"{ENGINE_PREFIX}/asset/three-winding-transformers/",
    "transformer": f"{ENGINE_PREFIX}/asset/transformers/",
    "hubserver": f"{HUB_PREFIX}/server/servers/",
    "hubserverversion": f"{HUB_PREFIX}/server/versions/",
}

CUSTOM_PATHS_MAP = {
    "set-asset-attribute": "{prefix}/assets/{asset}/set-attribute/",
    "get-asset-attribute": "{prefix}/assets/{asset}/get-attribute/",
    "decrypt-secret": "{prefix}/secrets/decrypt/",
    "routine-status": "{prefix}/component/routines/{routine}/update_status/",
    "server-status": "{prefix}/server/servers/{server}/update-status/",
    "set-asset-metadata": "{prefix}/asset/metadata/{metadata}/set/",
    "set-asset-relationship": "{prefix}/asset/relations/{relationship}/set/",
}
