# Generated by Django 3.2.8 on 2021-10-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('connector_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PowerTransformerTapChanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_step', models.FloatField(default=0)),
                ('low_step', models.FloatField(default=0)),
                ('neutral_step', models.FloatField(default=0)),
                ('neturalU', models.FloatField(default=0)),
                ('step_voltage_increment', models.FloatField(default=0)),
                ('tap_position', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('base_voltage', models.IntegerField()),
            ],
            bases=('splight_storage.asset',),
        ),
        migrations.CreateModel(
            name='FTPConnector',
            fields=[
                ('connectorinterface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.connectorinterface')),
                ('ftp_connection_string', models.CharField(max_length=200, null=True)),
            ],
            bases=('splight_storage.connectorinterface',),
        ),
        migrations.CreateModel(
            name='LocalFSConnector',
            fields=[
                ('connectorinterface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.connectorinterface')),
                ('path', models.FilePathField(max_length=10, null=True)),
                ('query', models.CharField(default=None, max_length=100, null=True)),
                ('sort_by', models.CharField(default=None, max_length=100, null=True)),
            ],
            bases=('splight_storage.connectorinterface',),
        ),
        migrations.CreateModel(
            name='PowerTransformerWinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_voltage', models.FloatField()),
                ('b', models.FloatField()),
                ('b0', models.FloatField()),
                ('g', models.FloatField()),
                ('g0', models.FloatField()),
                ('r', models.FloatField()),
                ('r0', models.FloatField()),
                ('x', models.FloatField()),
                ('x0', models.FloatField()),
                ('ratedS', models.FloatField()),
                ('ratedU', models.FloatField()),
                ('rground', models.FloatField()),
                ('xground', models.FloatField()),
                ('current_limit', models.FloatField()),
                ('code_connect', models.CharField(max_length=10)),
                ('type', models.CharField(default='primary', max_length=10)),
                ('tap_changer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.powertransformertapchanger')),
                ('bus', models.ForeignKey(db_column='bus', on_delete=django.db.models.deletion.CASCADE, related_name='windings', to='splight_storage.bus')),
            ],
        ),
        migrations.CreateModel(
            name='PowerTransformer',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('windings', models.ManyToManyField(to='splight_storage.PowerTransformerWinding')),
            ],
            bases=('splight_storage.asset',),
        ),
    ]
