# Generated by Django 3.2.8 on 2021-10-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('splight_storage.ftpconnector', 'ftp connector'), ('splight_storage.localfsconnector', 'local fs connector')], db_index=True, max_length=255)),
                ('ftp_connection_string', models.CharField(max_length=200, null=True)),
                ('path', models.FilePathField(max_length=10, null=True)),
                ('query', models.CharField(default=None, max_length=100, null=True)),
                ('sort_by', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('splight_storage.powertransformerwinding', 'power transformer winding'), ('splight_storage.powertransformertapchanger', 'power transformer tap changer'), ('splight_storage.powertransformer', 'power transformer')], db_index=True, max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('base_voltage', models.FloatField(null=True)),
                ('b', models.FloatField(null=True)),
                ('b0', models.FloatField(null=True)),
                ('g', models.FloatField(null=True)),
                ('g0', models.FloatField(null=True)),
                ('r', models.FloatField(null=True)),
                ('r0', models.FloatField(null=True)),
                ('x', models.FloatField(null=True)),
                ('x0', models.FloatField(null=True)),
                ('ratedS', models.FloatField(null=True)),
                ('ratedU', models.FloatField(null=True)),
                ('rground', models.FloatField(null=True)),
                ('xground', models.FloatField(null=True)),
                ('bus', models.TextField(max_length=10, null=True)),
                ('current_limit', models.FloatField(null=True)),
                ('code_connect', models.FloatField(null=True)),
                ('tap_changer', models.TextField(max_length=100, null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splight_storage.connectorinterface')),
            ],
        ),
        migrations.CreateModel(
            name='FTPConnector',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('splight_storage.connectorinterface',),
        ),
        migrations.CreateModel(
            name='LocalFSConnector',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('splight_storage.connectorinterface',),
        ),
        migrations.CreateModel(
            name='PowerTransformer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('splight_storage.asset',),
        ),
        migrations.CreateModel(
            name='PowerTransformerTapChanger',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('splight_storage.asset',),
        ),
        migrations.CreateModel(
            name='PowerTransformerWinding',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('splight_storage.asset',),
        ),
        migrations.AddField(
            model_name='asset',
            name='windings',
            field=models.ManyToManyField(to='splight_storage.PowerTransformerWinding'),
        ),
    ]
