# Generated by Django 3.2.8 on 2021-10-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subclass', models.CharField(default='', max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'Sensor'), (1, 'Device'), (2, 'Part Of Device')], null=True)),
                ('name', models.CharField(max_length=100)),
                ('connector_id', models.PositiveIntegerField(blank=True, null=True)),
                ('connector_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalOfferComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoadResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exponent_model', models.BooleanField(default=True)),
                ('p_constant_power', models.FloatField(null=True)),
                ('p_constant_current', models.FloatField(null=True)),
                ('p_constant_impedance', models.FloatField(null=True)),
                ('q_constant_power', models.FloatField(null=True)),
                ('q_constant_current', models.FloatField(null=True)),
                ('q_constant_impedance', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.IntegerField()),
                ('q', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PowerTransformerTapChanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_step', models.FloatField(default=0)),
                ('low_step', models.FloatField(default=0)),
                ('neutral_step', models.FloatField(default=0)),
                ('neturalU', models.FloatField(default=0)),
                ('step_voltage_increment', models.FloatField(default=0)),
                ('tap_position', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BusAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('base_voltage', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.asset',),
        ),
        migrations.CreateModel(
            name='FTPConnector',
            fields=[
                ('connectorinterface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.connectorinterface')),
                ('ftp_connection_string', models.CharField(max_length=200, null=True)),
            ],
            bases=('splight_storage.connectorinterface',),
        ),
        migrations.CreateModel(
            name='GeneratingUnitAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('governor_SCD', models.FloatField(default=0)),
                ('max_length', models.FloatField(default=0)),
                ('maximum_allowable_spinning_reserve', models.FloatField(default=0)),
                ('min_operating_P', models.FloatField(default=0)),
                ('nominal_P', models.FloatField(default=0)),
                ('normal_PF', models.FloatField(default=0)),
                ('startup_cost', models.FloatField(default=0)),
                ('variable_cost', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.asset',),
        ),
        migrations.CreateModel(
            name='LineAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('base_voltage', models.FloatField(default=0)),
                ('current_limit', models.FloatField(default=0)),
                ('b0ch', models.FloatField(default=0)),
                ('bch', models.FloatField(default=0)),
                ('g0ch', models.FloatField(default=0)),
                ('gch', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('r', models.FloatField(default=0)),
                ('x', models.FloatField(default=0)),
                ('x0', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.asset',),
        ),
        migrations.CreateModel(
            name='LocalFSConnector',
            fields=[
                ('connectorinterface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.connectorinterface')),
                ('path', models.FilePathField(max_length=10, null=True)),
                ('query', models.CharField(default=None, max_length=100, null=True)),
                ('sort_by', models.CharField(default=None, max_length=100, null=True)),
            ],
            bases=('splight_storage.connectorinterface',),
        ),
        migrations.CreateModel(
            name='PowerTransformerAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.asset',),
        ),
        migrations.CreateModel(
            name='SwitchAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('base_voltage', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.asset',),
        ),
        migrations.CreateModel(
            name='RunningDigitalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('network_name', models.CharField(max_length=100)),
                ('digital_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running', to='splight_storage.digitaloffer')),
            ],
        ),
        migrations.AddField(
            model_name='digitaloffer',
            name='components',
            field=models.ManyToManyField(related_name='digital_offers', to='splight_storage.DigitalOfferComponent'),
        ),
        migrations.CreateModel(
            name='ShuntAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('base_voltage', models.FloatField(default=0)),
                ('b0_per_sections', models.FloatField(default=0)),
                ('b_per_sections', models.FloatField(default=0)),
                ('g0_per_sections', models.FloatField(default=0)),
                ('g_per_sections', models.FloatField(default=0)),
                ('max_sections', models.IntegerField(default=0)),
                ('current_section', models.IntegerField(default=0)),
                ('bus', models.ForeignKey(db_column='bus', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shunts', to='splight_storage.busasset')),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.asset',),
        ),
        migrations.CreateModel(
            name='PowerTransformerWinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_voltage', models.FloatField(default=0)),
                ('b', models.FloatField(default=0)),
                ('b0', models.FloatField(default=0)),
                ('g', models.FloatField(default=0)),
                ('g0', models.FloatField(default=0)),
                ('r', models.FloatField(default=0)),
                ('r0', models.FloatField(default=0)),
                ('x', models.FloatField(default=0)),
                ('x0', models.FloatField(default=0)),
                ('ratedS', models.FloatField(default=0)),
                ('ratedU', models.FloatField(default=0)),
                ('rground', models.FloatField(default=0)),
                ('xground', models.FloatField(default=0)),
                ('current_limit', models.FloatField(default=0)),
                ('code_connect', models.CharField(default='NA', max_length=10)),
                ('type', models.CharField(default='primary', max_length=10)),
                ('tap_changer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.powertransformertapchanger')),
                ('bus', models.ForeignKey(db_column='bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='windings', to='splight_storage.busasset')),
                ('transformer', models.ForeignKey(db_column='transformer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='windings', to='splight_storage.powertransformerasset')),
            ],
        ),
        migrations.CreateModel(
            name='MachineAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('machine_type', models.CharField(max_length=100)),
                ('maxQ', models.IntegerField(default=0)),
                ('minQ', models.IntegerField(default=0)),
                ('qPercent', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
                ('r0', models.IntegerField(default=0)),
                ('r2', models.IntegerField(default=0)),
                ('rared', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('x0', models.IntegerField(default=0)),
                ('x2', models.IntegerField(default=0)),
                ('base_voltage', models.FloatField(default=0)),
                ('control_v', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(db_column='bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='splight_storage.busasset')),
                ('generating_unit', models.ForeignKey(db_column='generating_unit', on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='splight_storage.generatingunitasset')),
                ('power_flow', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='splight_storage.powerflow')),
                ('regulated_bus', models.ForeignKey(db_column='regulated_bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulated_machines', to='splight_storage.busasset')),
            ],
            bases=('splight_storage.asset',),
        ),
        migrations.CreateModel(
            name='LoadAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('base_voltage', models.IntegerField(default=0)),
                ('bus', models.ForeignKey(db_column='bus', on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='splight_storage.busasset')),
                ('load_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='load', to='splight_storage.loadresponse')),
                ('power_flow', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load', to='splight_storage.powerflow')),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.asset',),
        ),
        migrations.AddField(
            model_name='busasset',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='splight_storage.lineasset'),
        ),
        migrations.AddField(
            model_name='busasset',
            name='switch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='splight_storage.switchasset'),
        ),
    ]
