# Generated by Django 3.2.8 on 2021-10-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exponent_model', models.BooleanField(default=True)),
                ('p_constant_power', models.FloatField(null=True)),
                ('p_constant_current', models.FloatField(null=True)),
                ('p_constant_impedance', models.FloatField(null=True)),
                ('q_constant_power', models.FloatField(null=True)),
                ('q_constant_current', models.FloatField(null=True)),
                ('q_constant_impedance', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.IntegerField()),
                ('q', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('base_voltage', models.IntegerField(null=True)),
                ('load_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='load', to='splight_storage.loadresponse')),
                ('powerflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='load', to='splight_storage.powerflow')),
            ],
            bases=('splight_storage.asset',),
        ),
    ]
