# Generated by Django 3.2.8 on 2021-10-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busasset',
            name='line',
        ),
        migrations.RemoveField(
            model_name='busasset',
            name='switch',
        ),
        migrations.AddField(
            model_name='lineasset',
            name='buses',
            field=models.ManyToManyField(related_name='lines', to='splight_storage.BusAsset'),
        ),
        migrations.AddField(
            model_name='switchasset',
            name='buses',
            field=models.ManyToManyField(related_name='switches', to='splight_storage.BusAsset'),
        ),
    ]
