# Generated by Django 3.2.8 on 2021-10-18 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalOfferComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RunningDigitalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('network_name', models.CharField(max_length=100)),
                ('digital_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running', to='splight_storage.digitaloffer')),
            ],
        ),
        migrations.AddField(
            model_name='digitaloffer',
            name='components',
            field=models.ManyToManyField(related_name='digital_offers', to='splight_storage.DigitalOfferComponent'),
        ),
    ]
