# Generated by Django 3.2.8 on 2021-10-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineasset',
            name='bus',
            field=models.ForeignKey(db_column='bus', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='machines', to='splight_storage.busasset'),
        ),
        migrations.AlterField(
            model_name='machineasset',
            name='regulated_bus',
            field=models.ForeignKey(db_column='regulated_bus', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='regulated_machines', to='splight_storage.busasset'),
        ),
        migrations.AlterField(
            model_name='powertransformerwinding',
            name='bus',
            field=models.ForeignKey(db_column='bus', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='windings', to='splight_storage.busasset'),
        ),
        migrations.AlterField(
            model_name='shuntasset',
            name='bus',
            field=models.ForeignKey(db_column='bus', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shunts', to='splight_storage.busasset'),
        ),
    ]
