# Generated by Django 3.2.8 on 2021-10-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0002_alter_networkrelation_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkrelation',
            name='network',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='splight_storage.network'),
        ),
    ]
