# Generated by Django 3.2.8 on 2021-10-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0002_auto_20211018_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineasset',
            old_name='type',
            new_name='machine_type',
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.IntegerField(choices=[(0, 'Sensor'), (1, 'Device'), (2, 'Part Of Device')], default=0),
        ),
    ]
