# Generated by Django 3.2.8 on 2021-10-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('splight_storage', '0002_auto_20211020_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='connector_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='powerflow',
            name='p',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='powerflow',
            name='q',
            field=models.IntegerField(default=0),
        ),
    ]
