# Generated by Django 3.2.8 on 2021-10-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0002_load_loadresponse_powerflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shunt',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('base_voltage', models.IntegerField(default=0)),
            ],
            bases=('splight_storage.asset',),
        ),
        migrations.AlterField(
            model_name='load',
            name='base_voltage',
            field=models.IntegerField(default=0),
        ),
    ]
