# Generated by Django 3.2.8 on 2021-10-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0003_auto_20211018_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.IntegerField(choices=[(0, 'Sensor'), (1, 'Device'), (2, 'Part Of Device')], null=True),
        ),
    ]
