# Generated by Django 3.2.8 on 2021-10-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0004_alter_asset_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='object_id',
            new_name='connector_id',
        ),
        migrations.AddField(
            model_name='asset',
            name='subclass',
            field=models.CharField(default='', max_length=100),
        ),
    ]
