# Generated by Django 3.2.8 on 2021-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0004_alter_networkrelation_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineasset',
            name='control_v',
            field=models.FloatField(default=0),
        ),
    ]
