# Generated by Django 3.2.8 on 2021-10-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0004_auto_20211014_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratingUnit',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('governor_SCD', models.FloatField(default=0)),
                ('max_length', models.FloatField(default=0)),
                ('maximum_allowable_spinning_reserve', models.FloatField(default=0)),
                ('min_operating_P', models.FloatField(default=0)),
                ('nominal_P', models.FloatField(default=0)),
                ('normal_PF', models.FloatField(default=0)),
                ('startup_cost', models.FloatField(default=0)),
                ('variable_cost', models.FloatField(default=0)),
            ],
            bases=('splight_storage.asset',),
        ),
        migrations.RemoveField(
            model_name='line',
            name='type',
        ),
    ]
