# Generated by Django 3.2.8 on 2021-10-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0005_alter_machineasset_control_v'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='runningdigitaloffer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='runningdigitaloffer',
            name='network_name',
        ),
        migrations.AddField(
            model_name='runningdigitaloffer',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digital_offers', to='splight_storage.networkrelation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant'),
        ),
        migrations.AddField(
            model_name='connectorinterface',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant'),
        ),
        migrations.AddField(
            model_name='network',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant'),
        ),
        migrations.AddField(
            model_name='runningdigitaloffer',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant'),
        ),
    ]
