# Generated by Django 3.2.8 on 2021-10-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0005_auto_20211018_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busasset',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='splight_storage.lineasset'),
        ),
        migrations.AlterField(
            model_name='busasset',
            name='switch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='splight_storage.switchasset'),
        ),
        migrations.AlterField(
            model_name='machineasset',
            name='bus',
            field=models.ForeignKey(db_column='bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='splight_storage.busasset'),
        ),
        migrations.AlterField(
            model_name='machineasset',
            name='regulated_bus',
            field=models.ForeignKey(db_column='regulated_bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulated_machines', to='splight_storage.busasset'),
        ),
        migrations.AlterField(
            model_name='powertransformerwinding',
            name='bus',
            field=models.ForeignKey(db_column='bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='windings', to='splight_storage.busasset'),
        ),
        migrations.AlterField(
            model_name='powertransformerwinding',
            name='tap_changer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='splight_storage.powertransformertapchanger'),
        ),
    ]
