# Generated by Django 3.2.8 on 2021-10-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0006_auto_20211018_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powertransformerasset',
            name='windings',
            field=models.ManyToManyField(related_name='transformers', to='splight_storage.PowerTransformerWinding'),
        ),
    ]
