# Generated by Django 3.2.8 on 2021-10-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0006_auto_20211022_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningdigitaloffer',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digital_offers', to='splight_storage.network'),
        ),
    ]
