# Generated by Django 3.2.8 on 2021-10-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0006_alter_asset_tags'),
        ('splight_storage', '0007_alter_runningdigitaloffer_network'),
    ]

    operations = [
    ]
