# Generated by Django 3.2.8 on 2021-10-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0008_auto_20211018_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powertransformerasset',
            name='windings',
        ),
        migrations.AddField(
            model_name='powertransformerwinding',
            name='transformer',
            field=models.ForeignKey(db_column='transformer', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='windings', to='splight_storage.powertransformerasset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
