# Generated by Django 3.2.8 on 2021-10-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0008_merge_20211025_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkrelation',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='networkrelation',
            name='network',
        ),
        migrations.RemoveField(
            model_name='runningdigitaloffer',
            name='network',
        ),
        migrations.AddField(
            model_name='runningdigitaloffer',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digital_offers', to='splight_storage.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(to='splight_storage.Tag'),
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='NetworkRelation',
        ),
    ]
