# Generated by Django 3.2.8 on 2021-10-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0009_auto_20211020_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadasset',
            name='bus',
            field=models.ForeignKey(db_column='bus', on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='splight_storage.busasset'),
        ),
        migrations.AlterField(
            model_name='powertransformerwinding',
            name='tap_changer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.powertransformertapchanger'),
        ),
        migrations.AlterField(
            model_name='powertransformerwinding',
            name='transformer',
            field=models.ForeignKey(db_column='transformer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='windings', to='splight_storage.powertransformerasset'),
        ),
    ]
