# Generated by Django 3.2.8 on 2021-10-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0009_auto_20211026_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='splight_storage.Tag'),
        ),
    ]
