# Generated by Django 3.2.8 on 2021-10-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0010_alter_asset_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfsconnector',
            name='path',
            field=models.FilePathField(blank=True, max_length=10, null=True),
        ),
    ]
