# Generated by Django 3.2.8 on 2021-10-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0011_alter_localfsconnector_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
