# Generated by Django 3.2.8 on 2021-10-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0012_asset_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineasset',
            name='r',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machineasset',
            name='r0',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machineasset',
            name='r2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machineasset',
            name='rared',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machineasset',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machineasset',
            name='x0',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machineasset',
            name='x2',
            field=models.FloatField(default=0),
        ),
    ]
