# Generated by Django 3.2.8 on 2021-10-28 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0013_change_power_flow_fields_to_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineasset',
            name='bus',
            field=models.ForeignKey(blank=True, db_column='bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='splight_storage.busasset'),
        ),
        migrations.AlterField(
            model_name='machineasset',
            name='maxQ',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machineasset',
            name='minQ',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machineasset',
            name='regulated_bus',
            field=models.ForeignKey(blank=True, db_column='regulated_bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulated_machines', to='splight_storage.busasset'),
        ),
    ]
