# Generated by Django 3.2.8 on 2021-10-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0013_auto_20211028_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerflow',
            name='p',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='powerflow',
            name='q',
            field=models.FloatField(default=0),
        ),
    ]
