# Generated by Django 3.2.8 on 2021-10-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0015_rename_MachineAsset_to_Machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
