# Generated by Django 3.2.8 on 2021-10-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0015_alter_fields_machineAsset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachineAsset',
            new_name='Machine',
        ),
    ]
