# Generated by Django 3.2.8 on 2021-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0016_added_name_to_Machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
