# Generated by Django 3.2.8 on 2021-11-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0018_alter_Asset_unique_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('mnemotechnic', models.CharField(max_length=100, unique=True)),
                ('infotechnic', models.CharField(max_length=100, unique=True)),
                ('technical_key', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('ip', models.GenericIPAddressField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.asset',),
        ),
        migrations.AlterField(
            model_name='localfsconnector',
            name='path',
            field=models.FilePathField(max_length=300, null=True),
        ),
    ]
