# Generated by Django 3.2.8 on 2021-11-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0018_alter_Asset_unique_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='localfsconnector',
            name='path',
            field=models.FilePathField(max_length=300, null=True),
        ),
    ]
