# Generated by Django 3.2.8 on 2021-11-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0018_alter_Asset_unique_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localfsconnector',
            name='path',
            field=models.FilePathField(max_length=300, null=True),
        ),
    ]
