# Generated by Django 3.2.8 on 2021-11-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0019_create_RelayAsset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relayasset',
            name='ip',
        ),
    ]
