# Generated by Django 3.2.8 on 2021-11-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0019_alter_localfsconnector_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localfsconnector',
            name='connectorinterface_ptr',
        ),
        migrations.AddField(
            model_name='asset',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='FTPConnector',
        ),
        migrations.DeleteModel(
            name='LocalFSConnector',
        ),
    ]
