# Generated by Django 3.2.8 on 2021-11-09 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0020_alter_Asset_latitud_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='longitude',
        ),
        migrations.CreateModel(
            name='Geopoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='geopoints',
            field=models.ManyToManyField(blank=True, to='splight_storage.Geopoint'),
        ),
    ]
