# Generated by Django 3.2.8 on 2021-11-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0021_create_model_Geopoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='connector_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='connector_type',
        ),
        migrations.DeleteModel(
            name='ConnectorInterface',
        ),
    ]
