# Generated by Django 3.2.8 on 2021-11-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0022_alter_Asset_create_status_field'),
        ('splight_storage', '0022_auto_20211111_1000'),
    ]

    operations = [
    ]
