# Generated by Django 3.2.8 on 2021-11-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0024_relayasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonutSensorAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('angle', models.DecimalField(decimal_places=2, max_digits=2)),
                ('orientation', models.CharField(max_length=100)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donuts', to='splight_storage.lineasset')),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.asset',),
        ),
    ]
