# Generated by Django 3.2.8 on 2021-11-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0026_alter_mdoel_DonutSensorAsset_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donutsensorasset',
            name='angle',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
