# Generated by Django 3.2.8 on 2021-11-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0028_network_openvpn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='name',
        ),
        migrations.AddField(
            model_name='network',
            name='auth_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='network',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
