# Generated by Django 3.2.8 on 2021-11-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0029_alter_model_network_create_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='openvpn',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='openvpn',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openvpn',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
