# Generated by Django 3.2.8 on 2021-11-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0030_alter_OpenVPN_add_fields_username_password_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenVPN',
            new_name='OpenVPNNetwork',
        ),
    ]
