# Generated by Django 3.2.8 on 2021-11-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0028_lineasset_line_type'),
        ('splight_storage', '0031_rename_openvpn_openvpnnetwork'),
    ]

    operations = [
    ]
