# Generated by Django 3.2.8 on 2021-11-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0032_merge_20211123_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geopoint',
            options={'ordering': ['-pk']},
        ),
    ]
