# Generated by Django 3.2.8 on 2021-11-30 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0034_connector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='splight_storage.network'),
        ),
    ]
