# Generated by Django 3.2.8 on 2021-11-30 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0035_alter_connector_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('field', models.CharField(max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_mappings', to='splight_storage.asset')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_mappings', to='splight_storage.connector')),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('field', models.CharField(max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_mapping', to='splight_storage.asset')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_mappings', to='splight_storage.connector')),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant')),
            ],
            options={
                'unique_together': {('field', 'asset')},
            },
        ),
    ]
