# Generated by Django 3.2.8 on 2021-12-01 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0037_auto_20211130_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='network',
        ),
        migrations.AddField(
            model_name='connector',
            name='port',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connector',
            name='protocol',
            field=models.CharField(choices=[('dnp3', 'DNP3'), ('iec6', 'IEC61850')], default='dnp3', max_length=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServerConnector',
            fields=[
                ('connector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.connector')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_connectors', to='splight_storage.network')),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.connector',),
        ),
        migrations.CreateModel(
            name='ClientConnector',
            fields=[
                ('connector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.connector')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_connectors', to='splight_storage.network')),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.connector',),
        ),
    ]
