# Generated by Django 3.2.8 on 2021-12-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0038_auto_20211201_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='hodor_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
