# Generated by Django 3.2.8 on 2021-12-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0039_network_hodor_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='network',
            name='type',
        ),
    ]
