# Generated by Django 3.2.8 on 2021-12-15 16:22

from django.db import migrations, models
import django.db.models.deletion
import splight_storage.models.network


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0040_auto_20211210_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='splight_storage.connector'),
        ),
        migrations.AlterField(
            model_name='openvpnnetwork',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=splight_storage.models.network.upload_to),
        ),
    ]
