# Generated by Django 3.2.8 on 2021-12-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0041_alter_openvpnnetwork_file'),
        ('splight_storage', '0041_auto_20211215_1622'),
    ]

    operations = [
    ]
