# Generated by Django 3.2.8 on 2021-12-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0042_merge_20211217_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openvpnnetwork',
            options={'ordering': ['-id']},
        ),
    ]
