# Generated by Django 3.2.8 on 2021-12-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0043_alter_openvpnnetwork_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconnector',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_connectors', to='splight_storage.network'),
        ),
        migrations.AlterField(
            model_name='connector',
            name='ip',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='serverconnector',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_connectors', to='splight_storage.network'),
        ),
    ]
