# Generated by Django 3.2.8 on 2021-12-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0044_auto_20211227_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='connector',
        ),
        migrations.AddField(
            model_name='clientmapping',
            name='connector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='splight_storage.clientconnector'),
        ),
        migrations.AddField(
            model_name='servermapping',
            name='connector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='splight_storage.serverconnector'),
        ),
    ]
