# Generated by Django 3.2.8 on 2021-12-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0045_auto_20211227_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='hodor_address',
        ),
    ]
