# Generated by Django 3.2.8 on 2022-01-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0046_remove_network_hodor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='extra_config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
