# Generated by Django 3.2.8 on 2022-01-04 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0046_remove_network_hodor_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('base_voltage', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.asset',),
        ),
        migrations.CreateModel(
            name='RefMapping',
            fields=[
                ('mapping_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.mapping')),
            ],
            bases=('splight_storage.mapping',),
        ),
        migrations.CreateModel(
            name='ValueMapping',
            fields=[
                ('mapping_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.mapping')),
                ('value', models.CharField(max_length=40)),
            ],
            bases=('splight_storage.mapping',),
        ),
        # migrations.RemoveField(
        #     model_name='donutsensorasset',
        #     name='asset_ptr',
        # ),
        migrations.RemoveField(
            model_name='donutsensorasset',
            name='line',
        ),
        # migrations.RemoveField(
        #     model_name='generatingunitasset',
        #     name='asset_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='lineasset',
        #     name='asset_ptr',
        # ),
        migrations.RemoveField(
            model_name='lineasset',
            name='buses',
        ),
        # migrations.RemoveField(
        #     model_name='loadasset',
        #     name='asset_ptr',
        # ),
        migrations.RemoveField(
            model_name='loadasset',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='loadasset',
            name='load_response',
        ),
        migrations.RemoveField(
            model_name='loadasset',
            name='power_flow',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='generating_unit',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='power_flow',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='regulated_bus',
        ),
        # migrations.RemoveField(
        #     model_name='powertransformerasset',
        #     name='asset_ptr',
        # ),
        migrations.RemoveField(
            model_name='powertransformerwinding',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='powertransformerwinding',
            name='tap_changer',
        ),
        migrations.RemoveField(
            model_name='powertransformerwinding',
            name='transformer',
        ),
        # migrations.RemoveField(
        #     model_name='relayasset',
        #     name='asset_ptr',
        # ),
        # migrations.RemoveField(
        #     model_name='shuntasset',
        #     name='asset_ptr',
        # ),
        migrations.RemoveField(
            model_name='shuntasset',
            name='bus',
        ),
        # migrations.RemoveField(
        #     model_name='switchasset',
        #     name='asset_ptr',
        # ),
        migrations.RemoveField(
            model_name='switchasset',
            name='buses',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='path',
        ),
        migrations.RemoveField(
            model_name='servermapping',
            name='field',
        ),
        migrations.AddField(
            model_name='clientmapping',
            name='path',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='servermapping',
            name='path',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='BusAsset',
        ),
        migrations.DeleteModel(
            name='DonutSensorAsset',
        ),
        migrations.DeleteModel(
            name='GeneratingUnitAsset',
        ),
        migrations.DeleteModel(
            name='LineAsset',
        ),
        migrations.DeleteModel(
            name='LoadAsset',
        ),
        migrations.DeleteModel(
            name='LoadResponse',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='PowerFlow',
        ),
        migrations.DeleteModel(
            name='PowerTransformerAsset',
        ),
        migrations.DeleteModel(
            name='PowerTransformerTapChanger',
        ),
        migrations.DeleteModel(
            name='PowerTransformerWinding',
        ),
        migrations.DeleteModel(
            name='RelayAsset',
        ),
        migrations.DeleteModel(
            name='ShuntAsset',
        ),
        migrations.DeleteModel(
            name='SwitchAsset',
        ),
        migrations.AddField(
            model_name='valuemapping',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_mappings', to='splight_storage.asset'),
        ),
        migrations.AddField(
            model_name='valuemapping',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_mappings', to='splight_storage.attribute'),
        ),
        migrations.AddField(
            model_name='refmapping',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_mappings', to='splight_storage.asset'),
        ),
        migrations.AddField(
            model_name='refmapping',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_mappings', to='splight_storage.attribute'),
        ),
        migrations.AddField(
            model_name='refmapping',
            name='ref_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referers', to='splight_storage.asset'),
        ),
        migrations.AddField(
            model_name='refmapping',
            name='ref_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referers', to='splight_storage.attribute'),
        ),
        migrations.AddField(
            model_name='clientmapping',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_mappings', to='splight_storage.attribute'),
        ),
        migrations.AddField(
            model_name='servermapping',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_mappings', to='splight_storage.attribute'),
        ),
        migrations.AlterUniqueTogether(
            name='clientmapping',
            unique_together={('attribute', 'asset')},
        ),
        migrations.AlterUniqueTogether(
            name='valuemapping',
            unique_together={('attribute', 'asset')},
        ),
        migrations.AlterUniqueTogether(
            name='refmapping',
            unique_together={('attribute', 'asset')},
        ),
        migrations.RemoveField(
            model_name='clientmapping',
            name='field',
        ),
    ]
