# Generated by Django 3.2.8 on 2022-01-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0047_auto_20220104_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
