# Generated by Django 3.2.8 on 2022-01-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0047_connector_extra_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connector',
            old_name='ip',
            new_name='host',
        ),
    ]
