# Generated by Django 3.2.8 on 2022-01-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0048_delete_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('base_voltage', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('splight_storage.asset',),
        ),
    ]
