# Generated by Django 3.2.8 on 2022-01-05 12:13

from django.db import migrations, models
import splight_storage.models.network


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0048_rename_ip_connector_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenVPNNetwork',
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='network',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=splight_storage.models.network.upload_to),
        ),
        migrations.AddField(
            model_name='network',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
