# Generated by Django 3.2.8 on 2022-01-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0049_bus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefMapping',
            new_name='ReferenceMapping',
        ),
    ]
