# Generated by Django 3.2.8 on 2022-01-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0049_auto_20220105_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
