# Generated by Django 3.2.8 on 2022-01-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0050_rename_refmapping_referencemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencemapping',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_mappings', to='splight_storage.asset'),
        ),
        migrations.AlterField(
            model_name='referencemapping',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_mappings', to='splight_storage.attribute'),
        ),
        migrations.AlterField(
            model_name='referencemapping',
            name='ref_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='splight_storage.asset'),
        ),
        migrations.AlterField(
            model_name='referencemapping',
            name='ref_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='splight_storage.attribute'),
        ),
    ]
