# Generated by Django 3.2.8 on 2022-01-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0050_network_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busasset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='clientconnector',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='connector',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='donutsensorasset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='generatingunitasset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='lineasset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='loadasset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='mapping',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='powertransformerasset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='relayasset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='runningdigitaloffer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='serverconnector',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='servermapping',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shuntasset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='switchasset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='connector',
            old_name='extra_config',
            new_name='extra_properties',
        ),
    ]
