# Generated by Django 3.2.8 on 2022-01-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0051_auto_20220106_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='protocol',
            field=models.CharField(choices=[('openvpn', 'openvpn')], default='openvpn', max_length=10),
        ),
    ]
