# Generated by Django 3.2.8 on 2022-01-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0051_auto_20220105_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant'),
        ),
    ]
