# Generated by Django 3.2.8 on 2022-01-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0052_network_protocol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverconnector',
            options={},
        ),
        migrations.AddField(
            model_name='serverconnector',
            name='external_port',
            field=models.IntegerField(default=8001),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='serverconnector',
            unique_together={('network', 'external_port')},
        ),
    ]
