# Generated by Django 3.2.8 on 2022-01-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0052_attribute_tenant'),
        ('splight_storage', '0053_auto_20220107_0830'),
    ]

    operations = [
    ]
