# Generated by Django 3.2.8 on 2022-01-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0054_merge_0052_attribute_tenant_0053_auto_20220107_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['-id']},
        ),
    ]
