# Generated by Django 3.2.8 on 2022-01-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0055_auto_20220110_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='asset_ptr',
        ),
        migrations.CreateModel(
            name='BaseAsset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('geopoints', models.ManyToManyField(blank=True, to='splight_storage.Geopoint')),
                ('tags', models.ManyToManyField(blank=True, to='splight_storage.Tag')),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='clientmapping',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_mappings', to='splight_storage.baseasset'),
        ),
        migrations.AlterField(
            model_name='referencemapping',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_mappings', to='splight_storage.baseasset'),
        ),
        migrations.AlterField(
            model_name='referencemapping',
            name='ref_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='splight_storage.baseasset'),
        ),
        migrations.AlterField(
            model_name='servermapping',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_mappings', to='splight_storage.baseasset'),
        ),
        migrations.AlterField(
            model_name='valuemapping',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_mappings', to='splight_storage.baseasset'),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
