# Generated by Django 3.2.8 on 2022-01-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0056_auto_20220110_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('baseasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.baseasset')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=('splight_storage.baseasset',),
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splight_storage.asset')),
                ('base_voltage', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=('splight_storage.asset',),
        ),
    ]
