# Generated by Django 3.2.8 on 2022-01-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0057_asset_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('high', 'high priority'), ('standard', 'standard priority')], default='high', max_length=8)),
                ('notification_message', models.TextField()),
                ('condition', models.CharField(choices=[('gt', 'greater'), ('lt', 'lower'), ('lte', 'lower or equal'), ('gte', 'greater or equal'), ('eq', 'equal'), ('ne', 'not equal')], default='gte', max_length=3)),
                ('value', models.FloatField()),
                ('renotify', models.BooleanField()),
                ('renotify_unit', models.CharField(choices=[('minutes', 'minutes'), ('hours', 'hours'), ('days', 'days'), ('months', 'months')], default='minutes', max_length=7, null=True)),
                ('renofity_time', models.IntegerField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_events', to='splight_storage.asset')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_events', to='splight_storage.attribute')),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
