# Generated by Django 3.2.8 on 2022-01-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0058_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='condition',
            field=models.CharField(choices=[('gt', 'Greater'), ('lt', 'Lower'), ('lte', 'Lower or equal'), ('gte', 'Greater or equal'), ('eq', 'Equal'), ('ne', 'Not equal')], default='gte', max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('high', 'High priority'), ('standard', 'Standard priority')], default='high', max_length=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='renotify_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('months', 'Months')], default='minutes', max_length=7, null=True),
        ),
    ]
