# Generated by Django 3.2.8 on 2022-01-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0059_auto_20220126_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='renofity_time',
            new_name='renotify_time',
        ),
    ]
