# Generated by Django 3.2.8 on 2022-02-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0061_auto_20220127_0603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trigger',
        ),
    ]
