# Generated by Django 3.2.8 on 2022-02-09 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0062_delete_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
