# Generated by Django 3.2.8 on 2022-02-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splight_storage', '0063_triggergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('high', 'High priority'), ('standard', 'Standard priority')], default='high', max_length=8)),
                ('notification_message', models.TextField()),
                ('condition', models.CharField(choices=[('gt', 'Greater'), ('lt', 'Lower'), ('lte', 'Lower or equal'), ('gte', 'Greater or equal'), ('eq', 'Equal'), ('ne', 'Not equal')], default='gte', max_length=3)),
                ('value', models.FloatField()),
                ('renotify', models.BooleanField()),
                ('renotify_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='minutes', max_length=7, null=True)),
                ('renotify_time', models.IntegerField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_triggers', to='splight_storage.asset')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_triggers', to='splight_storage.attribute')),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='splight_storage.tenant')),
                ('trigger_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='splight_storage.triggergroup')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
