# Generated by Django 3.2.8 on 2022-04-20 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
