# Generated by Django 3.2.8 on 2022-02-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
