# Generated by Django 3.2.8 on 2022-04-21 09:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0002_auto_20220420_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rule', models.CharField(max_length=300)),
                ('namespace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djatabase.namespace')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('collection', models.CharField(max_length=50)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('key', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('namespace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djatabase.namespace')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='triggergroup',
            name='namespace',
        ),
        migrations.DeleteModel(
            name='Trigger',
        ),
        migrations.DeleteModel(
            name='TriggerGroup',
        ),
        migrations.AddField(
            model_name='rule',
            name='variables',
            field=models.ManyToManyField(blank=True, null=True, to='djatabase.RuleVariable'),
        ),
    ]
