# Generated by Django 3.2.8 on 2022-02-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0002_asset_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='value',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='type',
            new_name='name',
        ),
    ]
