# Generated by Django 3.2.8 on 2022-04-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0003_auto_20220421_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='rule',
            new_name='statement',
        ),
    ]
