# Generated by Django 3.2.8 on 2022-02-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0003_auto_20220224_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencemapping',
            name='value',
        ),
    ]
