# Generated by Django 3.2.8 on 2022-02-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0004_remove_referencemapping_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RenameField(
            model_name='network',
            old_name='file',
            new_name='file_id',
        ),
    ]
