# Generated by Django 3.2.8 on 2022-03-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0004_remove_referencemapping_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default='default', max_length=255, primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=8)),
                ('message', models.TextField()),
                ('value', models.FloatField()),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
                ('trigger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djatabase.trigger')),
            ],
        ),
    ]
