# Generated by Django 3.2.8 on 2022-04-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0004_rename_rule_rule_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='variables',
            field=models.ManyToManyField(blank=True, to='djatabase.RuleVariable'),
        ),
    ]
