# Generated by Django 3.2.8 on 2022-03-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0005_names_descriptions_and_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
