# Generated by Django 3.2.8 on 2022-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0006_alter_tag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(max_length=100)),
                ('parameters', models.JSONField()),
            ],
        ),
    ]
