# Generated by Django 3.2.8 on 2022-04-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0006_auto_20220421_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='name',
            field=models.CharField(default='Rule', max_length=100),
        ),
    ]
