# Generated by Django 3.2.8 on 2022-04-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0007_auto_20220421_1842'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serverconnector',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='serverconnector',
            name='connector_ptr',
        ),
        migrations.RemoveField(
            model_name='serverconnector',
            name='network',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='extra_properties',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='host',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='password',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='port',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='username',
        ),
        migrations.RemoveField(
            model_name='network',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='network',
            name='password',
        ),
        migrations.RemoveField(
            model_name='network',
            name='username',
        ),
        migrations.AddField(
            model_name='connector',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='connector',
            name='tag_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='network',
            name='tag_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientmapping',
            name='connector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmappings', to='djatabase.connector'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='Network', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servermapping',
            name='connector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smappings', to='djatabase.connector'),
        ),
        migrations.DeleteModel(
            name='ClientConnector',
        ),
        migrations.DeleteModel(
            name='ServerConnector',
        ),
    ]
