# Generated by Django 3.2.8 on 2022-03-21 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0007_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_id', models.CharField(blank=True, max_length=100, null=True)),
                ('algorithm_id', models.CharField(blank=True, max_length=100, null=True)),
                ('settings', models.JSONField()),
                ('namespace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djatabase.namespace')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='runningdigitaloffer',
            name='digital_offer',
        ),
        migrations.RemoveField(
            model_name='runningdigitaloffer',
            name='namespace',
        ),
        migrations.RemoveField(
            model_name='runningdigitaloffer',
            name='tag',
        ),
        migrations.DeleteModel(
            name='DigitalOffer',
        ),
        migrations.DeleteModel(
            name='DigitalOfferComponent',
        ),
        migrations.DeleteModel(
            name='RunningDigitalOffer',
        ),
    ]
