# Generated by Django 3.2.8 on 2022-03-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0008_runner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runner',
            old_name='settings',
            new_name='parameters',
        ),
    ]
