# Generated by Django 3.2.8 on 2022-04-26 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0008_auto_20220426_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('parameters', models.JSONField()),
                ('namespace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djatabase.namespace')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='connector',
            name='tag_id',
        ),
        migrations.RemoveField(
            model_name='network',
            name='tag_id',
        ),
        migrations.DeleteModel(
            name='Runner',
        ),
    ]
