# Generated by Django 3.2.8 on 2022-04-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0008_chartitem_color'),
        ('djatabase', '0009_auto_20220426_0855'),
    ]

    operations = [
    ]
