# Generated by Django 3.2.8 on 2022-03-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0009_rename_settings_runner_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='protocol',
            field=models.CharField(choices=[('dnp3', 'DNP3'), ('iec6', 'IEC61850'), ('ftp', 'FTP')], max_length=4),
        ),
    ]
