# Generated by Django 3.2.8 on 2022-05-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
