# Generated by Django 3.2.8 on 2022-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0012_auto_20220401_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartitem',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chartitem',
            name='split_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chartitem',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
