# Generated by Django 3.2.8 on 2022-05-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0012_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
