# Generated by Django 3.2.8 on 2022-04-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0013_auto_20220405_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
