# Generated by Django 3.2.8 on 2022-05-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0013_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='readme_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='readme_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='readme_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
