# Generated by Django 3.2.8 on 2022-04-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0014_chart_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Algorithm',
        ),
        migrations.RenameField(
            model_name='runner',
            old_name='algorithm_id',
            new_name='version',
        ),
    ]
