# Generated by Django 3.2.8 on 2022-05-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0014_auto_20220513_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartitem',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
