# Generated by Django 3.2.8 on 2022-04-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0015_auto_20220406_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='chart_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='djatabase.chartitem'),
        ),
    ]
