# Generated by Django 3.2.8 on 2022-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0015_chartitem_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='privacy_policy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='tenant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
