# Generated by Django 3.2.8 on 2022-04-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0015_auto_20220406_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
