# Generated by Django 3.2.8 on 2022-05-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0016_auto_20220526_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='privacy_policy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connector',
            name='tenant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='privacy_policy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='tenant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
