# Generated by Django 3.2.8 on 2022-04-11 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0016_alter_filter_chart_item'),
        ('djatabase', '0016_clientmapping_period'),
    ]

    operations = [
    ]
