# Generated by Django 3.2.8 on 2022-04-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0016_auto_20220407_1333'),
        ('djatabase', '0017_merge_20220411_1204'),
    ]

    operations = [
    ]
