# Generated by Django 3.2.8 on 2022-06-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0017_auto_20220527_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgregateItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criteria', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_agregate_items', to='djatabase.chart')),
                ('namespace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djatabase.namespace')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
