# Generated by Django 3.2.8 on 2022-06-03 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0018_agregateitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smappings', to='djatabase.asset')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smappings', to='djatabase.attribute')),
                ('namespace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djatabase.namespace')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
