# Generated by Django 3.2.8 on 2022-06-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0019_auto_20220603_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
