# Generated by Django 3.2.8 on 2022-06-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0019_auto_20220603_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='impact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='impact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
