# Generated by Django 3.2.8 on 2022-06-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0020_chart_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='aggregate_criteria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='aggregate_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AgregateItem',
        ),
    ]
