# Generated by Django 3.2.8 on 2022-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0021_auto_20220608_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mappingrule',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mappingrule',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
