# Generated by Django 3.2.8 on 2022-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0021_auto_20220608_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingrule',
            name='operator',
            field=models.CharField(choices=[('gt', 'Greater than'), ('ge', 'Greater or equal'), ('lt', 'Lower than'), ('le', 'Lower than or equal'), ('eq', 'Equal')], default='eq', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mappingrule',
            name='severity',
            field=models.CharField(choices=[('system', 'System'), ('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='asset_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='attribute_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='rule_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(choices=[('system', 'System'), ('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_type',
            field=models.CharField(choices=[('Algorithm', 'Algorithm'), ('Network', 'Network'), ('Connector', 'Connector')], max_length=20, null=True),
        ),
    ]
