# Generated by Django 3.2.8 on 2022-06-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0022_auto_20220615_1337'),
        ('djatabase', '0022_edge_graph_node'),
    ]

    operations = [
    ]
