# Generated by Django 3.2.8 on 2022-06-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0022_auto_20220614_1335'),
        ('djatabase', '0023_merge_0022_auto_20220615_1337_0022_edge_graph_node'),
    ]

    operations = [
    ]
