# Generated by Django 3.2.8 on 2022-06-22 08:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0024_merge_20220616_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='privacy_policy',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='privacy_policy',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='network',
            name='privacy_policy',
        ),
        migrations.RemoveField(
            model_name='network',
            name='tenant',
        ),
        migrations.CreateModel(
            name='MonthBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateTimeField()),
                ('billings', models.JSONField()),
                ('discount', models.JSONField(null=True)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('total_price_without_discount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('paid', models.BooleanField()),
                ('namespace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djatabase.namespace')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('pricing', models.JSONField()),
                ('discounts', models.JSONField()),
                ('computing_time_measurement_per_hour', models.BooleanField()),
                ('namespace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djatabase.namespace')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
