# Generated by Django 3.2.8 on 2022-06-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0025_auto_20220627_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='color',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='color',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='handle_orientation',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='node',
            name='position_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='position_y',
            field=models.IntegerField(default=0),
        ),
    ]
