# Generated by Django 3.2.8 on 2022-07-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0026_auto_20220630_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='color',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='color',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='handle_orientation',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
