# Generated by Django 3.2.8 on 2022-07-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0028_auto_20220701_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='image',
            new_name='external_resource',
        ),
        migrations.AddField(
            model_name='chart',
            name='external_resource_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chartitem',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chartitem',
            name='position_x',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chartitem',
            name='position_y',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chartitem',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
