# Generated by Django 3.2.8 on 2022-07-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0029_auto_20220711_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='asset',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djatabase.asset'),
        ),
    ]
