# Generated by Django 3.2.8 on 2022-07-19 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0029_auto_20220711_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('abi_json', models.JSONField(default=dict)),
            ],
        ),
    ]
