# Generated by Django 3.2.8 on 2022-07-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0029_auto_20220708_0838'),
        ('djatabase', '0029_auto_20220711_1338'),
    ]

    operations = [
    ]
