# Generated by Django 3.2.8 on 2022-07-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0030_blockchaincontract'),
        ('djatabase', '0030_edge_asset'),
    ]

    operations = [
    ]
