# Generated by Django 3.2.8 on 2022-07-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0030_edge_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='fill_color',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
