# Generated by Django 3.2.8 on 2022-07-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0031_merge_0030_blockchaincontract_0030_edge_asset'),
        ('djatabase', '0031_node_fill_color'),
    ]

    operations = [
    ]
