# Generated by Django 3.2.8 on 2022-07-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0032_merge_20220719_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchaincontract',
            old_name='account_id',
            new_name='address',
        ),
    ]
