# Generated by Django 3.2.8 on 2022-07-22 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0033_rename_account_id_blockchaincontract_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainContractSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(max_length=100, null=True)),
                ('attribute_id', models.CharField(max_length=100, null=True)),
                ('contract_id', models.CharField(max_length=100, null=True)),
                ('namespace', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djatabase.namespace')),
            ],
            options={
                'unique_together': {('attribute_id', 'asset_id', 'contract_id')},
            },
        ),
    ]
