# Generated by Django 3.2.8 on 2022-07-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0034_blockchaincontractsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchaincontractsubscription',
            name='last_checkpoint',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
