# Generated by Django 3.2.8 on 2022-07-22 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0035_blockchaincontractsubscription_last_checkpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchaincontractsubscription',
            name='last_checkpoint',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
