# Generated by Django 3.2.8 on 2022-07-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0036_alter_blockchaincontractsubscription_last_checkpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='handle_orientation',
        ),
        migrations.AddField(
            model_name='edge',
            name='source_handle',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='target_handle',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
