# Generated by Django 3.2.8 on 2022-07-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0038_auto_20220727_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchaincontractsubscription',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='blockchaincontractsubscription',
            unique_together=set(),
        ),
    ]
