# Generated by Django 3.2.8 on 2022-08-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0038_auto_20220727_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingitem',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='billingitem',
            name='namespace',
        ),
        migrations.RemoveField(
            model_name='deploymentbillingitem',
            name='billingitem_ptr',
        ),
        migrations.RemoveField(
            model_name='monthbilling',
            name='namespace',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='BillingItem',
        ),
        migrations.DeleteModel(
            name='DeploymentBillingItem',
        ),
        migrations.DeleteModel(
            name='MonthBilling',
        ),
    ]
