# Generated by Django 3.2.8 on 2022-07-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djatabase', '0038_auto_20220729_1140'),
        ('djatabase', '0039_auto_20220729_1235'),
    ]

    operations = [
    ]
