name: Upload library
on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    name: uploading lib to pypi
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
