name: "Running Tests"
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'firstgha'
jobs:
  tests:
    runs-on: ubuntu-latest
    name: running tests
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: python setup.py install
      - run: python manage.py migrate
      - run: pytest .