name: "Running Tests"
on:
  pull_request:
    branches:
      - "**"
jobs:
  tests:
    runs-on: ubuntu-latest
    name: running tests
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo make install
      - run: sudo make test
