# used when creating a pull request
# this step runs the tests, coding style and validates that the version is
# release and greater than the version of master and pypi
name: Pre Release
on:
  pull_request:
    types:
      [opened, synchronize]
    branches:
      - master

env:
  LIBRARY_NAME: "splight-lib"

jobs:
  run_tests_and_coding_style:
    runs-on: ubuntu-latest
    name: Verify library tests and coding style
    steps:
      - name: Checkout to feature branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Setup poetry
        run: pip install poetry==1.7.0

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Run tests
        run: make test

      # TODO: discuss about following steps
      # - name: Run flake8
      #   run: make flake8

      # - name: Run isort
      #   run: make isort

      # - name: Run black
      #   run: make black

  verify_version:
    runs-on: ubuntu-latest
    name: Verify version is a valid release version and is higher than last PyPi package and master version
    steps:
      # get master version
      - name: Checkout to master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Get version from master branch
        run: |
          if [ -f "setup.py" ]; then
            echo "MASTER_VERSION=$(grep -E 'version' setup.py | awk -F'\"' '{ print $2 }')" >> "$GITHUB_ENV"
          else
            echo "MASTER_VERSION=$(grep version pyproject.toml | awk '{print $3}' | tr -d '\"')" >> "$GITHUB_ENV"
          fi

      # get current branch version
      - name: Checkout to feature branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Get version from feature branch
        run: |
          if [ -f "setup.py" ]; then
            echo "CURRENT_VERSION=$(grep -E 'version' setup.py | awk -F'\"' '{ print $2 }')" >> "$GITHUB_ENV"
          else
            echo "CURRENT_VERSION=$(grep version pyproject.toml | awk '{print $3}' | tr -d '\"')" >> "$GITHUB_ENV"
          fi

      # validate versions
      - name: Verify version is a valid release version
        run: python .github/workflows/scripts/check_release_version.py ${{ env.CURRENT_VERSION }}

      - name: Verify version is greater than last pypi uploaded version
        run: python .github/workflows/scripts/check_pypi_version.py ${{ env.CURRENT_VERSION }} $LIBRARY_NAME

      - name: Verify version is greater than master version
        run: python .github/workflows/scripts/check_master_version.py ${{ env.MASTER_VERSION }} ${{ env.CURRENT_VERSION }}
